DROP TABLE PESSOA CASCADE CONSTRAINTS;
DROP TABLE ENDERECO CASCADE CONSTRAINTS;
DROP TABLE TELEFONE_PESSOA CASCADE CONSTRAINTS;
DROP TABLE DIRETOR CASCADE CONSTRAINTS;
DROP TABLE FUNCIONARIO CASCADE CONSTRAINTS;
DROP TABLE ATRACAO CASCADE CONSTRAINTS;
DROP TABLE TRABALHA CASCADE CONSTRAINTS;
DROP TABLE PROGRAMACAO CASCADE CONSTRAINTS;
DROP TABLE PATROCINADOR CASCADE CONSTRAINTS;
DROP TABLE TELEFONE_PATROCINADOR CASCADE CONSTRAINTS;
DROP TABLE EXIBE_PROPAGANDA CASCADE CONSTRAINTS;
DROP TABLE ESTUDIO CASCADE CONSTRAINTS;
DROP TABLE TELEFONE_ESTUDIO CASCADE CONSTRAINTS;
DROP TABLE EXIBICAO CASCADE CONSTRAINTS;
DROP TABLE PLANTAO CASCADE CONSTRAINTS;
DROP TABLE EXIBICAO_PLANTAO CASCADE CONSTRAINTS;

DROP SEQUENCE cod_atracao;
DROP SEQUENCE cod_estudio;
DROP SEQUENCE cod_programacao;

CREATE TABLE PESSOA(
	
	cpf VARCHAR2(11) NOT NULL,
	nome VARCHAR2(150) NOT NULL,
	sexo CHAR NOT NULL,
	salario VARCHAR2(9) NOT NULL 

);

ALTER TABLE PESSOA ADD CONSTRAINT pessoa_pk PRIMARY KEY(cpf);

CREATE TABLE ENDERECO(
	
	cpf_pessoa VARCHAR2(11) NOT NULL,
	cep VARCHAR2(8) NOT NULL,
	cidade VARCHAR2(80) NOT NULL,
	bairro VARCHAR2(80) NOT NULL, 
	rua VARCHAR2(100) NOT NULL,
	num_casa VARCHAR2(6) NOT NULL

);

ALTER TABLE ENDERECO ADD CONSTRAINT endereco_pk PRIMARY KEY(cpf_pessoa);
ALTER TABLE ENDERECO ADD CONSTRAINT endereco_cpf_pessoa_fk FOREIGN KEY(cpf_pessoa) REFERENCES PESSOA(cpf) ON DELETE CASCADE;

CREATE TABLE TELEFONE_PESSOA(

	cpf_pessoa VARCHAR2(11) NOT NULL,
	telefone VARCHAR2(9) NOT NULL

);

ALTER TABLE TELEFONE_PESSOA ADD CONSTRAINT telefone_pessoa_pk PRIMARY KEY(cpf_pessoa, telefone);
ALTER TABLE TELEFONE_PESSOA ADD CONSTRAINT telefone_pessoa_cpf_pessoa_fk FOREIGN KEY(cpf_pessoa) REFERENCES PESSOA(cpf) ON DELETE CASCADE;


CREATE TABLE DIRETOR(
	
	cpf_diretor VARCHAR2(11) NOT NULL,
	part_lucro VARCHAR2(9) NOT NULL

);

ALTER TABLE DIRETOR ADD CONSTRAINT diretor_pk PRIMARY KEY(cpf_diretor);
ALTER TABLE DIRETOR ADD CONSTRAINT diretor_cpf_diretor_fk FOREIGN KEY(cpf_diretor) REFERENCES PESSOA(cpf) ON DELETE CASCADE;

CREATE TABLE FUNCIONARIO(

	cpf_funcionario VARCHAR(11) NOT NULL,
	cpf_coordenador VARCHAR(11),
	funcao VARCHAR(50) NOT NULL
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT funcionario_pk PRIMARY KEY(cpf_funcionario);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT funcionario_cpf_funcionario_fk FOREIGN KEY(cpf_funcionario) REFERENCES PESSOA(cpf) ON DELETE CASCADE;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT funcionario_cpf_coordenador_fk FOREIGN KEY(cpf_coordenador) REFERENCES FUNCIONARIO(cpf_funcionario);

CREATE TABLE ATRACAO(

	cod_atracao NUMBER NOT NULL,
	cpf_diretor VARCHAR2(11) NOT NULL,
	nome VARCHAR2(100) NOT NULL, 
	classificacao VARCHAR2(3) NOT NULL,
	tipo VARCHAR2(25) NOT NULL
);

ALTER TABLE ATRACAO ADD CONSTRAINT atracao_pk PRIMARY KEY(cod_atracao);
ALTER TABLE ATRACAO ADD CONSTRAINT atracao_cpf_diretor_fk FOREIGN KEY(cpf_diretor) REFERENCES DIRETOR(cpf_diretor);
CREATE SEQUENCE cod_atracao START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;


CREATE TABLE TRABALHA(

	cpf_funcionario VARCHAR2(11) NOT NULL,
	cod_atracao NUMBER NOT NULL
);

ALTER TABLE TRABALHA ADD CONSTRAINT trabalha_pk PRIMARY KEY(cpf_funcionario, cod_atracao);
ALTER TABLE TRABALHA ADD CONSTRAINT trabalha_cpf_funcionario_fk FOREIGN KEY(cpf_funcionario) REFERENCES FUNCIONARIO(cpf_funcionario) ON DELETE CASCADE;
ALTER TABLE TRABALHA ADD CONSTRAINT trabalha_cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE CASCADE;

CREATE TABLE PROGRAMACAO(

	cod_programacao NUMBER NOT NULL,
	data_hora TIMESTAMP NOT NULL
);

ALTER TABLE PROGRAMACAO ADD CONSTRAINT programacao_pk PRIMARY KEY(cod_programacao);
CREATE SEQUENCE cod_programacao START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;


CREATE TABLE PATROCINADOR(

	cnpj VARCHAR2(14) NOT NULL,
	cod_atracao NUMBER NOT NULL

);

ALTER TABLE PATROCINADOR ADD CONSTRAINT patrocinador_pk PRIMARY KEY(cnpj);
ALTER TABLE PATROCINADOR ADD CONSTRAINT patrocinador_cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE CASCADE;


CREATE TABLE TELEFONE_PATROCINADOR(

	cnpj_patrocinador VARCHAR2(14) NOT NULL,
	telefone VARCHAR2(9) NOT NULL

);

ALTER TABLE TELEFONE_PATROCINADOR ADD CONSTRAINT telefone_patrocinador_pk PRIMARY KEY(cnpj_patrocinador, telefone);
ALTER TABLE TELEFONE_PATROCINADOR ADD CONSTRAINT tel_patro_cnpj_patrocinador_fk FOREIGN KEY(cnpj_patrocinador) REFERENCES PATROCINADOR(cnpj) ON DELETE CASCADE;

CREATE TABLE EXIBE_PROPAGANDA(
	
	cnpj_patrocinador VARCHAR2(14) NOT NULL,
	data_hora TIMESTAMP NOT NULL,
	conteudo VARCHAR2(200) NOT NULL
);

ALTER TABLE EXIBE_PROPAGANDA ADD CONSTRAINT exibe_propaganda_pk PRIMARY KEY(cnpj_patrocinador, data_hora);
ALTER TABLE EXIBE_PROPAGANDA ADD CONSTRAINT e_prop_cnpj_patrocinador_fk FOREIGN KEY(cnpj_patrocinador) REFERENCES PATROCINADOR(cnpj) ON DELETE CASCADE;

CREATE TABLE ESTUDIO(
	
	cod_estudio NUMBER NOT NULL,
	nome_simbolico VARCHAR2(80) NOT NULL,
	tamanho VARCHAR2(9) NOT NULL
	
);

ALTER TABLE ESTUDIO ADD CONSTRAINT estudio_pk PRIMARY KEY(cod_estudio);
CREATE SEQUENCE cod_estudio START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE TABLE TELEFONE_ESTUDIO(

	cod_estudio NUMBER NOT NULL,
	telefone VARCHAR2(9) NOT NULL

);

ALTER TABLE TELEFONE_ESTUDIO ADD CONSTRAINT telefone_estudio_pk PRIMARY KEY(cod_estudio, telefone);
ALTER TABLE TELEFONE_ESTUDIO ADD CONSTRAINT tel_estudio_cod_estudio_fk FOREIGN KEY(cod_estudio) REFERENCES ESTUDIO(cod_estudio) ON DELETE CASCADE;

CREATE TABLE EXIBICAO(
	
	cod_programacao NUMBER NOT NULL,
	cod_atracao NUMBER NOT NULL,
	cod_estudio NUMBER NOT NULL
);

ALTER TABLE EXIBICAO ADD CONSTRAINT exibicao_pk PRIMARY KEY(cod_programacao, cod_atracao, cod_estudio);
ALTER TABLE EXIBICAO ADD CONSTRAINT exibicao_cod_programacao_fk FOREIGN KEY(cod_programacao) REFERENCES PROGRAMACAO(cod_programacao) ON DELETE SET NULL;
ALTER TABLE EXIBICAO ADD CONSTRAINT exibicao_cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE SET NULL;
ALTER TABLE EXIBICAO ADD CONSTRAINT exibicao_cod_estudio_fk FOREIGN KEY(cod_estudio) REFERENCES ESTUDIO(cod_estudio) ON DELETE SET NULL;

CREATE TABLE PLANTAO(
	
	data_hora TIMESTAMP NOT NULL,
	ocorrencia VARCHAR2(400) NOT NULL
);

ALTER TABLE PLANTAO ADD CONSTRAINT data_hora_pk PRIMARY KEY(data_hora);


CREATE TABLE EXIBICAO_PLANTAO(
	
	data_hora_plantao TIMESTAMP NOT NULL,
	cod_programacao NUMBER NOT NULL,
	cod_atracao NUMBER NOT NULL,
	cod_estudio NUMBER NOT NULL
);

ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT exibicao_plantao_pk PRIMARY KEY(data_hora_plantao, cod_programacao, cod_atracao, cod_estudio);
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT e_plantao_data_hora_plantao_fk FOREIGN KEY(data_hora_plantao) REFERENCES PLANTAO(data_hora) ON DELETE SET NULL;
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT e_plantao_cod_programacao_fk FOREIGN KEY(cod_programacao) REFERENCES PROGRAMACAO(cod_programacao) ON DELETE SET NULL;
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT e_plantao_cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE SET NULL;
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT e_plantao_cod_estudio_fk FOREIGN KEY(cod_estudio) REFERENCES ESTUDIO(cod_estudio) ON DELETE SET NULL;


