CREATE TABLE 'PESSOA'(
	
	'cpf' VARCHAR2(11) NOT NULL,
	'nome' VARCHAR2(150) NOT NULL,
	'sexo' CHAR NOT NULL,
	'salario' VARCHAR2(9) NOT NULL 

);

ALTER TABLE PESSOA ADD CONSTRAINT pessoa_pk PRIMARY KEY(cpf);

CREATE TABLE 'ENDERECO'(
	
	'cpf_pessoa' VARCHAR2(11) NOT NULL,
	'cep' VARCHAR2(8) NOT NULL,
	'cidade' VARCHAR2(80) NOT NULL,
	'bairro' VARCHAR2(80) NOT NULL, 
	'rua' VARCHAR2(100) NOT NULL,
	'num_casa' VARCHAR2(6) NOT NULL

);

ALTER TABLE ENDERECO ADD CONSTRAINT endereco_pk PRIMARY KEY(cpf_pessoa);
ALTER TABLE ENDERECO ADD CONSTRAINT endereco_fk FOREIGN KEY(cpf_pessoa) REFERENCES PESSOA(cpf) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE 'TELEFONE_PESSOA'(

	'cpf_pessoa' VARCHAR2(11) NOT NULL,
	'telefone' VARCHAR2(9) NOT NULL

);

ALTER TABLE TELEFONE_PESSOA ADD CONSTRAINT telefone_pessoa_pk PRIMARY KEY(cpf_pessoa, telefone);
ALTER TABLE TELEFONE_PESSOA ADD CONSTRAINT telefone_pessoa_fk FOREIGN KEY(cpf_pessoa) REFERENCES PESSOA(cpf) ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE 'DIRETOR'(
	
	'cpf_diretor' VARCHAR2(11) NOT NULL,
	'part_lucro' VARCHAR2(9) NOT NULL

);

ALTER TABLE DIRETOR ADD CONSTRAINT diretor_pk PRIMARY KEY(cpf_diretor);
ALTER TABLE DIRETOR ADD CONSTRAINT cpf_diretor_fk FOREIGN KEY(cpf_diretor) REFERENCES PESSOA(cpf) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE 'FUNCIONARIO'(

	'cpf_funcionario' VARCHAR(11) NOT NULL,
	'cpf_coordenador' VARCHAR(11) NOT NULL,
	'funcao' VARCHAR(50) NOT NULL
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT funcionario_pk PRIMARY KEY(cpf_funcionario);
ALTER TABLE FUNCIONARIO ADD CONSTRAINT cpf_funcionario_fk FOREIGN KEY(cpf_funcionario) REFERENCES PESSOA(cpf) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE FUNCIONARIO ADD CONSTRAINT cpf_coordenador_fk FOREIGN KEY(cpf_coordenador) REFERENCES FUNCIONARIO(cpf_funcionario);

CREATE TABLE 'ATRACAO'(

	'cod_atracao' NUMBER NOT NULL,
	'cpf_diretor' VARCHAR2(11) NOT NULL,
	'nome' VARCHAR2(100) NOT NULL, 
	'classificacao' VARCHAR2(3) NOT NULL,
	'tipo' VARCHAR2(25) NOT NULL
);

ALTER TABLE ATRACAO ADD CONSTRAINT atracao_pk PRIMARY KEY(cod_atracao);
ALTER TABLE ATRACAO ADD CONSTRAINT cpf_diretor_fk FOREIGN KEY(cpf_diretor) REFERENCES DIRETOR(cpf_diretor);
CREATE SEQUENCE cod_atracao START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;


CREATE TABLE 'TRABALHA'(

	'cpf_funcionario' VARCHAR(11) NOT NULL,
	'cod_atracao' NUMBER NOT NULL,
);

ALTER TABLE TRABALHA ADD CONSTRAINT trabalha_pk PRIMARY KEY(cpf_funcionario, cod_atracao);
ALTER TABLE TRABALHA ADD CONSTRAINT cpf_funcionario_fk FOREIGN KEY(cpf_funcionario) REFERENCES FUNCIONARIO(cpf_funcionario) ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE TRABALHA ADD CONSTRAINT cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE_TABLE 'PROGRAMACAO'(

	'cod_programacao' NUMBER NOT NULL,
	'data_hora' TIMESTAMP NOT NULL,
);

ALTER TABLE PROGRAMACAO ADD CONSTRAINT programacao_pk PRIMARY KEY(cod_programacao);
CREATE SEQUENCE cod_programacao START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;


CREATE_TABLE 'PATROCINADOR'(

	'cnpj' VARCHAR(14) NOT NULL,
	'cod_atracao' NUMBER NOT NULL,

);

ALTER TABLE PATROCINADOR ADD CONSTRAINT patrocinador_pk PRIMARY KEY(cnpj);
ALTER TABLE PATROCINADOR ADD CONSTRAINT cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE CASCADE ON UPDATE CASCADE;


CREATE TABLE 'TELEFONE_PATROCINADOR'(

	'cnpj_patrocinador' VARCHAR2(14) NOT NULL,
	'telefone' VARCHAR2(9) NOT NULL

);

ALTER TABLE TELEFONE_PATROCINADOR ADD CONSTRAINT telefone_patrocinador_pk PRIMARY KEY(cnpj_patrocinador, telefone);
ALTER TABLE TELEFONE_PATROCINADOR ADD CONSTRAINT cnpj_patrocinador_fk FOREIGN KEY(cnpj_patrocinador) REFERENCES PATROCINADOR(cnpj) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE 'EXIBE_PROPAGANDA'(
	
	'cnpj_patrocinador' VARCHAR2(14) NOT NULL,
	'data_hora' TIMESTAMP NOT NULL,
	'conteudo' VARCHAR2(200) NOT NULL,
);

ALTER TABLE EXIBE_PROPAGANDA ADD CONSTRAINT exibe_propaganda_pk PRIMARY KEY(cnpj_patrocinador, data_hora);
ALTER TABLE EXIBE_PROPAGANDA ADD CONSTRAINT cnpj_patrocinador_fk FOREIGN KEY(cnpj_patrocinador) REFERENCES PATROCINADOR(cnpj) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE 'ESTUDIO'(
	
	'cod_estudio' NUMBER NOT NULL,
	'nome_simbolico' VARCHAR2(80) NOT NULL,
	'tamanho' VARCHAR2(9) NOT NULL,
	
);

ALTER TABLE ESTUDIO ADD CONSTRAINT estudio_pk PRIMARY KEY(cod_estudio);
CREATE SEQUENCE cod_estudio START WITH 1 INCREMENT BY 1 NOMAXVALUE NOCYCLE;

CREATE TABLE 'TELEFONE_ESTUDIO'(

	'cod_estudio' VARCHAR2(11) NOT NULL,
	'telefone' VARCHAR2(9) NOT NULL

);

ALTER TABLE TELEFONE_ESTUDIO ADD CONSTRAINT telefone_estudio_pk PRIMARY KEY(cod_estudio, telefone);
ALTER TABLE TELEFONE_ESTUDIO ADD CONSTRAINT cod_estudio_fk FOREIGN KEY(cod_estudio) REFERENCES ESTUDIO(cod_estudio) ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE 'EXIBICAO'(
	
	'cod_programacao' NUMBER NOT NULL,
	'cod_atracao' NUMBER NOT NULL,
	'cod_estudio' NUMBER NOT NULL,
);

ALTER TABLE EXIBICAO ADD CONSTRAINT exibicao_pk PRIMARY KEY(cod_programacao, cod_atracao, cod_estudio);
ALTER TABLE EXIBICAO ADD CONSTRAINT cod_programacao_fk FOREIGN KEY(cod_programcao) REFERENCES PROGRAMACAO(cod_programacao) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EXIBICAO ADD CONSTRAINT cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EXIBICAO ADD CONSTRAINT cod_estudio_fk FOREIGN KEY(cod_estudio) REFERENCES ESTUDIO(cod_estudio) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE TABLE 'PLANTAO'(
	
	'data_hora' TIMESTAMP NOT NULL,
	'ocorrencia' VARCHAR2(400) NOT NULL,
);

ALTER TABLE PLANTAO ADD CONSTRAINT data_hora_pk PRIMARY KEY(data_hora);


CREATE TABLE 'EXIBICAO_PLANTAO'(
	
	'data_hora_plantao' TIMESTAMP NOT NULL,
	'cod_programacao' NUMBER NOT NULL,
	'cod_atracao' NUMBER NOT NULL,
	'cod_estudio' NUMBER NOT NULL,
);

ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT exibicao_plantao_pk PRIMARY KEY(data_hora_plantao, cod_programacao, cod_atracao, cod_estudio);
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT data_hora_plantao_fk FOREIGN KEY(data_hora_plantao) REFERENCES PLANTAO(data_hora) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT cod_programacao_fk FOREIGN KEY(cod_programcao) REFERENCES PROGRAMACAO(cod_programacao) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT cod_atracao_fk FOREIGN KEY(cod_atracao) REFERENCES ATRACAO(cod_atracao) ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE EXIBICAO_PLANTAO ADD CONSTRAINT cod_estudio_fk FOREIGN KEY(cod_estudio) REFERENCES ESTUDIO(cod_estudio) ON DELETE SET NULL ON UPDATE CASCADE;


